const coreDay = [{workout:'Rest',reps:1,weights:'None',time:0.5,id:2000},
                {workout:'Plank',reps:1,weights:'None',time:1,id:2001},
                {workout:'Panther Shoulder Tap',reps:12,weights:'None',time:0.5,id:2002},
                {workout:'Butterfly Sit-up',reps:12,weights:'None',time:0.5,id:2003},
                {workout:'Dead Bug',reps:12,weights:'None',time:0.5,id:2004},
                {workout:'Half Kneeling Wood Chop',reps:12,weights:'Medium',time:0.5,id:2005},
                {workout:'High Boat to Low Boat',reps:12,weights:'None',time:0.5,id:2006},
                {workout:'Body Saw',reps:12,weights:'None',time:0.5,id:2007},
                {workout:'Side Bend',reps:12,weights:'None',time:0.5,id:2008},
                {workout:'Jackknife',reps:12,weights:'None',time:0.5,id:2009},
                {workout:'Hollow Hold to Jackknife',reps:1,weights:'None',time:0.5,id:2010},
                {workout:'C-Curve Hold',reps:1,weights:'None',time:0.5,id:2011},
                {workout:'Leg Raise',reps:12,weights:'None',time:0.5,id:2012},
                {workout:'Row Your Boat',reps:12,weights:'None',time:0.5,id:2013},
                {workout:'Single-Leg Jackknife',reps:12,weights:'None',time:0.5,id:2014},
                {workout:'Plank Tap',reps:12,weights:'None',time:0.5,id:2015},
                {workout:'Hip Dip',reps:12,weights:'None',time:0.5,id:2016},
                {workout:'Bridge',reps:12,weights:'None',time:0.5,id:2017},
                {workout:'Crunch',reps:12,weights:'None',time:0.5,id:2018},
                {workout:'Supine Toe Tap',reps:12,weights:'None',time:0.5,id:2019},
      ];
export default coreDay;