const fullBodyDay = [{workout:'Rest',reps:1,weights:'None',time:0.5,id:4000},
                     {workout:'Burpees',reps:10,weights:'None',time:1,id:4001},
                     {workout:'Body Squats',reps:12,weights:'Medium',time:0.5,id:4002},
                     {workout:'Dumbbell Stepup',reps:12,weights:'Medium',time:0.5,id:4003},
                     {workout:'Pull Ups',reps:12,weights:'None',time:1,id:4004},
                     {workout:'Push ups',reps:12,weights:'None',time:0.5,id:4005},
                     {workout:'Triceps Dip',reps:15,weights:'None',time:0.5,id:4006},
                     {workout:'Jump Lunges',reps:12,weights:'None',time:1,id:4007},
                     {workout:'Kettlebell Swings',reps:12,weights:'Heavy',time:0.5,id:4008},
                     {workout:'Box Jumps',reps:12,weights:'None',time:1,id:4009},
                     {workout:'Resistance Band Glute Bridge',reps:12,weights:'None',time:0.5,id:4010},
                     {workout:'Side Lunges',reps:12,weights:'None',time:1,id:4011},
                     {workout:'Reverse Lunge to Overhead Press With Knee Drive',reps:12,weights:'Medium',time:1,id:4012},
                     {workout:'Crouching Tiger Push-up',reps:12,weights:'None',time:0.5,id:4013},
                     {workout:'Jumping Rope',reps:1,weights:'None',time:1,id:4014},
                     {workout:'Bulgarian Split Squat',reps:12,weights:'Medium',time:0.5,id:4015},
                     {workout:'Donkey Kicks',reps:12,weights:'None',time:0.5,id:4016},
                     {workout:'Bear Crawls',reps:12,weights:'None',time:0.5,id:4017},
                     {workout:'Mountain Climbers',reps:12,weights:'None',time:0.5,id:4018},
                     {workout:'Crab Walk Dips',reps:12,weights:'None',time:0.5,id:4019},
      ];
export default fullBodyDay;