const legDay = [{workout:'Rest',reps:1,weights:'None',time:0.5,id:1000},
                {workout:'Squat',reps:15,weights:'None',time:0.5,id:1001},
                {workout:'Bulgarian Split Squat',reps:12,weights:'Medium',time:0.5,id:1002},
                {workout:'Romanian Deadlift',reps:15,weights:'Heavy',time:0.5,id:1003},
                {workout:'Dumbbell Stepup',reps:12,weights:'Medium',time:0.5,id:1004},
                {workout:'Deadlift',reps:12,weights:'Heavy',time:0.5,id:1005},
                {workout:'Swiss Ball Leg Curl',reps:12,weights:'None',time:0.5,id:1006},
                {workout:'Single-Leg Romanian Deadlift',reps:15,weights:'Medium',time:0.5,id:1007},
                {workout:'Leg Press',reps:15,weights:'Heavy',time:0.5,id:1008},
                {workout:'Bodyweight Calf Raise',reps:15,weights:'Medium',time:0.5,id:1009},
                {workout:'Walking Lunge',reps:12,weights:'Medium',time:1,id:1010},
                {workout:'Reverse Lunge',reps:12,weights:'Medium',time:0.5,id:1011},
                {workout:'Dumbbell Squat',reps:12,weights:'Medium',time:0.5,id:1012},
                {workout:'Kettlebell Swing',reps:15,weights:'Medium',time:0.5,id:1013},
                {workout:'Jump Squat',reps:12,weights:'None',time:0.5,id:1014},
                {workout:'Skater Squat',reps:12,weights:'None',time:0.5,id:1015},
                {workout:'Barbell Hip Thrust',reps:12,weights:'Heavy',time:0.5,id:1016},
                {workout:'Glute Bridge Walkout',reps:12,weights:'None',time:0.5,id:1017},
                {workout:'Single-Leg Glute Bridge',reps:12,weights:'None',time:0.5,id:1018},
                {workout:'Swiss Ball Wall Squat',reps:12,weights:'None',time:0.5,id:1019}
      ];
export default legDay;